version: "3.8"
services:
  coffee-web:
    build: .
    volumes:
      - .:/coffee-web
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=3000
    stdin_open: true
